### ISSUE TITLE
Proper way of using refs for an internal schema

### ISSUE THREAD

**Issue by sepehr500** [ajv-validator/ajv#807]
I am trying to use JSON schema and ajv to validate data against a very large and complex schema. This means that there are many many separate json schemas being referenced using `$ref` to allow me to be DRY. I am running into an issue with best practices for using `$ref`. Since all of my JSON files reside on the same server, it seems silly to have my `$ref` use URI's that refer back to the same server. Doing this also makes testing difficult because I need to mock external requests to my own server to test my schema. Are URI's with `$ref` the best way of modulating a JSON schema, or is there a way to do it with internal file server references.

**Comment by epoberezkin** [comment]
> best practices for using $ref.

$refs are part of JSON schema spec, it’s better to address this question to JSON-Schema-org.

> Since all of my JSON files reside on the same server, it seems silly to have my $ref use URI's that refer back to the same server.

$refs can be relative URIs that are resolved based on the current schema $id, so you don’t have to use full URIs inside the schema with $id in the same domain.

> Doing this also makes testing difficult because I need to mock external requests to my own server to test my schema.

You don’t need to use any IO - you can add all your schemes either via ajv constructor option or via a method call. Also, please note that JSON schema spec specifically says that schema $ids are only identifiers and shouldn’t be treated as HTTP resource addresses where schema can be loaded from (although some schema providers make them available over HTTP).

> Are URI's with $ref the best way of modulating a JSON schema,

I believe so

 > or is there a way to do it with internal file server references.

You can use URIs that map to file locations - this mapping can be in loadSchema function (option).

**Comment by Sutikshan** [comment]
$id is mandatory for nested schemas to work. could you pls suggest method to give $id and the way to use it in $ref is given.
I have two schema , where one is referring to other. but when I try to add them both in ajv, it fails to validate with error

`{message: "can't resolve reference ../common/restricted-name.json from id #", missingRef: "common/restricted-name.json", missingSchema: "common/restricted-name.json"}`

```
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Personal Info",
  "description": "PersonalInfo.",
  "type": "object",
  "required": [
    "name",
  ],
  "properties": {
    "name": {
      "$ref": "../common/restricted-name.json"
    }
}
}
//restricted name-json in relative path
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "RestrictedName",
  "description": "RestrictedName defines a restricted name.  It is considered restricted as it does not include the non-editable field 'lastName'",
  "type": "object",
  "required": [
    "title",
    "firstName"
  ],
  "properties": {
    "title": {
      "type": "string"
    },
    "firstName": {
      "type": "string",
      "maxLength": 40
    },
    "middleNames": {
      "type": "string",
      "maxLength": 40
    }
  }
}
```

**Comment by Sutikshan** [comment]
Hi @sepehr500 Did u get your schemas ref each other correctly. I am trying following but still getting Ref Missing error by ajv.
My schemas are
```
personal-info.json

{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Personal Info",
  "description": "PersonalInfo defines a Personal Info payload, describing customer details for kyc purposes.",
  "type": "object",
  "required": [
    "name"
  ],
  "properties": {
    "name": {
      "$ref": "../common/restricted-name.json"
    },
}
}
// restricted-name.json in relative folder as mentioned above 
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "RestrictedName",
  "description": "RestrictedName defines a restricted name.  It is considered restricted as it does not include the non-editable field 'lastName'",
  "type": "object",
  "required": [
    "title",
    "firstName"
  ],
  "properties": {
    "title": {
      "type": "string"
    },
    "firstName": {
      "type": "string",
      "maxLength": 40
    },
    "middleNames": {
      "type": "string",
      "maxLength": 40
    }
  }
}
const restrictedName = require('activation/common/restricted-name.json');
const personalInfoSchema = require('activation/personal-info/personal-info.json');

ajv.addSchema(restrictedName, 'restricted-name').compile(restrictedName);
ajv.addSchema(personalInfoSchema, 'restricted-name').compile(personalInfoSchema);
```

**Comment by sepehr500** [comment]
@Sutikshan I ended up using https://github.com/BigstickCarpet/json-schema-ref-parser to deref, then passing it into ajv.

**Comment by epoberezkin** [comment]
@Sutikshan you cannot use a relative ref ("../common/restricted-name.json") in the schema without $id - is it relative to what? Ajv doesn't know which file is original schema is and doesn't do any I/O (unless you use compileAsync with loadSchema function).

As you added restrictedName with the reference "restricted-name" you should have used it in your schema: `"$ref": "restricted-name"` would have worked.
