### ISSUE TITLE
How to get $ref in errors?

### ISSUE THREAD

**Issue by ozum** [ajv-validator/ajv#88]
Hi,

I plan to create error messages based on $ref which caused errors. To do this, I need to get $ref in error object. You can see sample code below:

``` js
'use strict';
var Ajv = require('ajv');

var schema = {
    'type': 'object',
    'additionalProperties': false,
    'properties': {
        'mac': {
            '$ref': '#/definitions/macaddr'
        }
    },
    'definitions': {
        'macaddr': { type: 'string', pattern: '^c' }
    }
};

var data = {
    mac: 'a'
};

var ajv = Ajv({
    allErrors:  true,
    format:     'full',
    v5:         true
});

var validate = ajv.compile(schema);
var valid    = validate(data);

if (!valid) console.log(validate.errors);
```

which results with this error object:

```
[ { keyword: 'pattern',
    dataPath: '.mac',
    schemaPath: '.pattern',
    params: { pattern: '^c' },
    message: 'should match pattern "^c"' } ]
```

How can I obtain `#/definitions/macaddr` in error message?

Best Regards,

**Comment by epoberezkin** [comment]
By default referenced schemas are inlined in the compiled code (for performance reasons), in which case you will not have it. Try using option `inlineRefs: false`. In any case, #80 should resolve it.

**Comment by ozum** [comment]
Thank you for response. I tried to use combination of `inlineRefs: false`, `inlineRefs: true` with `jsonPointers: true`, I still cannot get `#/definitions/macaddr`in error object as below. In fact `inlineRefs` does not affect anything in my example code.

```
[ { keyword: 'pattern',
    dataPath: '/mac',
    schemaPath: '.pattern',
    params: { pattern: '^c' },
    message: 'should match pattern "^c"' } ]
```

**Comment by epoberezkin** [comment]
schemaPath is not in its final state indeed. jsonPointers only affects dataPath at the moment. At the moment error messages can be based on dataPath.

**Comment by ozum** [comment]
I'm trying to develop a Hapi.js validation plugin which would use ajv as validator. May I suggest this as a feature request then:

Building referenced schemas inlined in the compiled code is a nice decision. In this case, I think it would be beneficial to store/provide referenced schema's original path as a string without compromising performance. During validation most of the time we already would have non-compiled original JSON schema at hand. So it is possible to get other details from original schema using this string path in case we need them. As a result references would still be compiled inline and we can access details from original schema. Is it viable or are there any pitfalls?

BTW it would be much better if we can access details directly from error object, but I don't know if it would miss ajv's performance targets.

Thanks and regards,

**Comment by simon-p-r** [comment]
@ozum I have written a json schema based plugin for [hapi](https://github.com/simon-p-r/hapi-json-schema), it uses z-schema currently which I want to replace with ajv in near future.

**Comment by epoberezkin** [comment]
Thanks.

The immediate workaround I can suggest for error reporting is to either use some documented JSON-schema meta property (title, description or id) or to introduce some application specific one (e.g., `x-error-info`). If you use `verbose: true` the reference to the schema that triggered the error will be available in the error object and you can access the information you need.

For example, in your case if you change the schema in this way:

```
var schema = {
   // ...
    "definitions": {
        "macaddr": {
            "id": "#/definitions/macaddr"
            "type": "string",
            "pattern": "^c"
        }
    }
};

var ajv = Ajv({
    //...
    verbose: true
});
```

then `error.schema.id` will be "#/definitions/macaddr", which is what you need.

You can even set `id` in this definition as "#macaddr" and then you can refer to it using `{ "$ref": "#macaddr" }`.

There is still a plan for #80 to keep track of the current schema path in JSON-pointer format. The need to correctly handle referenced schemas in several scenarios is a complication and the reason I didn't have time to do it yet, but I don't think there are any pitfalls. So it'll get done.

**Comment by ozum** [comment]
Hi again,

That workaround would do the trick for me. However with Ajv v2.2.2, using id, verbose and even inlineRefs, I still cannot get any clue about which definition caused error:

``` js
'use strict';
var Ajv = require('ajv');

var schema = {
    'type': 'object',
    'additionalProperties': false,
    'properties': {
        'mac': {
            '$ref': '#/definitions/macaddr'
        }
    },
    'definitions': {
        'macaddr': {
            id: '#/definitions/macaddr',
            type: 'string',
            pattern: '^c'
        }
    }
};

var data = {
    mac: 'a'
};

var ajv = Ajv({
    allErrors:  true,
    verbose: true,
    format:     'full',
    inlineRefs: true,
    jsonPointers: true,
    v5:         true
});

var validate = ajv.compile(schema);
var valid    = validate(data);

if (!valid) console.log(validate.errors);
```

I got:

```
[ { keyword: 'pattern',
    dataPath: '/mac',
    schemaPath: '.pattern',
    params: { pattern: '^c' },
    message: 'should match pattern "^c"',
    schema: '^c',
    data: 'a' } ]
```

**Comment by epoberezkin** [comment]
You are right, parentSchema would do the trick if it existed :) I'll see what I can do.

**Comment by ozum** [comment]
Thanks for your support and effort.

**Comment by epoberezkin** [comment]
@ozum thanks for the patience :) I thought `parentSchema` is useful in any case so I added it to errors when option `verbose` is true (in version 2.3.0). `schemaPath` will be improved soon, but for now you can use the approach I suggested. I hope it helps.

`inlineRefs` and `jsonPointer` options don't affect it - `parentSchema` is simply the reference to the schema that contains the keyword that failed validation.

**Comment by ozum** [comment]
Awesome :) Thank you. This opens up way for custom error messages based on custom definitions such as "mac address", "IBAN" etc.
